import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

test('Git rejects attribution before committing and before pushing', () => {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const scratch = join(root, '.tmp');
  mkdirSync(scratch, { recursive: true });
  const fixture = mkdtempSync(join(scratch, 'attribution-'));
  const policy = join(root, 'scripts', 'check-attribution.mjs');
  const author = { GIT_AUTHOR_NAME: 'Giovanni Jecha', GIT_AUTHOR_EMAIL: '100841799+giovannijecha@users.noreply.github.com' };
  const env = { ...process.env, ...author, GIT_COMMITTER_NAME: author.GIT_AUTHOR_NAME, GIT_COMMITTER_EMAIL: author.GIT_AUTHOR_EMAIL, GIT_CONFIG_NOSYSTEM: '1' };
  for (const key of ['GIT_DIR', 'GIT_COMMON_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_CONFIG_PARAMETERS', 'GIT_CONFIG_COUNT']) delete env[key];
  env.GIT_CONFIG_GLOBAL = join(fixture, 'empty-config');
  writeFileSync(env.GIT_CONFIG_GLOBAL, '');
  const run = (program, args, options = {}) => spawnSync(program, args, { cwd: fixture, env, encoding: 'utf8', ...options });
  const git = (args, options = {}) => {
    const result = run('git', args, options);
    assert.equal(result.status, 0, result.stderr);
    return result.stdout.trim();
  };
  const denied = (result, label) => {
    assert.equal(result.status, 1, `${label}: ${result.stderr}`);
    assert.match(result.stderr, /Attribution check failed:/, label);
  };

  try {
    git(['init', '--quiet', '--template=', '--initial-branch=main']);
    const hooks = join(fixture, '.git', 'hooks');
    mkdirSync(hooks, { recursive: true });
    git(['config', 'core.hooksPath', hooks]);
    writeFileSync(join(hooks, 'commit-msg'), `#!/bin/sh\nexec "${process.execPath.replaceAll('\\', '/')}" "${policy.replaceAll('\\', '/')}" --pending "$1"\n`);
    writeFileSync(join(hooks, 'prepare-commit-msg'), `#!/bin/sh\nexec "${process.execPath.replaceAll('\\', '/')}" "${policy.replaceAll('\\', '/')}" --pending "$1"\n`);
    writeFileSync(join(hooks, 'pre-push'), `#!/bin/sh\nexec "${process.execPath.replaceAll('\\', '/')}" "${policy.replaceAll('\\', '/')}" --pre-push\n`);
    git(['commit', '--quiet', '--allow-empty', '-m', 'Check Codex and Claude CLI compatibility']);
    git(['commit', '--quiet', '--allow-empty', '-m', 'Fix code generated by the terminal']);
    const head = git(['rev-parse', 'HEAD']);
    const tree = git(['rev-parse', 'HEAD^{tree}']);
    const zeros = '0'.repeat(40);

    for (const message of [
      'Change\n\nCo-Authored-By: Fixture <fixture@example.invalid>',
      'Change\n\nco-authored-by: Fixture <fixture@example.invalid>',
      'Change\n\n🤖 Generated with an unknown assistant',
      'Change\n\nGenerated by an unknown assistant',
      'Change\n\nUnknown-Agent-Session: fixture',
    ]) denied(run('git', ['commit', '--allow-empty', '-m', message]), message);
    denied(run('git', ['commit', '--no-verify', '--allow-empty', '-m', 'Change\n\nCo-Authored-By: Fixture <fixture@example.invalid>']), 'Commit hook bypass');
    denied(run('git', ['commit', '--allow-empty', '-m', 'Change', '--author=Fixture <fixture@example.invalid>']), 'Author override');
    denied(run('git', ['commit', '--allow-empty', '-m', 'Change'], { env: { ...env, GIT_COMMITTER_NAME: 'Fixture', GIT_COMMITTER_EMAIL: 'fixture@example.invalid' } }), 'Committer override');
    assert.equal(git(['rev-parse', 'HEAD']), head, 'Rejected commits must not update HEAD');

    const unsafe = git(['commit-tree', tree, '-p', head], { input: 'Change\n\nCo-Authored-By: Fixture <fixture@example.invalid>\n' });
    const descendant = git(['commit-tree', tree, '-p', unsafe], { input: 'Normal descendant\n' });
    git(['config', 'attribution.baseline', head]);
    git(['config', '--add', 'attribution.baseline', '1'.repeat(40)]);
    denied(run(process.execPath, [policy, '--history', descendant]), 'Hidden ancestor attribution');
    const foreignAuthor = git(['commit-tree', tree, '-p', head], { input: 'Normal message\n', env: { ...env, GIT_AUTHOR_NAME: 'Fixture', GIT_AUTHOR_EMAIL: 'fixture@example.invalid' } });
    denied(run(process.execPath, [policy, '--history', foreignAuthor]), 'Foreign history author');
    const foreignCommitter = git(['commit-tree', tree, '-p', head], { input: 'Normal message\n', env: { ...env, GIT_COMMITTER_NAME: 'Fixture', GIT_COMMITTER_EMAIL: 'fixture@example.invalid' } });
    denied(run(process.execPath, [policy, '--history', foreignCommitter]), 'Foreign history committer');
    const webCommit = git(['commit-tree', tree, '-p', head], { input: 'Web merge\n', env: { ...env, GIT_COMMITTER_NAME: 'GitHub', GIT_COMMITTER_EMAIL: 'noreply@github.com' } });
    assert.equal(run(process.execPath, [policy, '--history', webCommit]).status, 0, 'GitHub web merge');
    denied(run(process.execPath, [policy, '--pre-push'], { input: `refs/heads/new ${descendant} refs/heads/new ${zeros}\n` }), 'New branch push');
    assert.equal(run(process.execPath, [policy, '--pre-push'], { input: `refs/heads/main ${head} refs/heads/new ${zeros}\n` }).status, 0, 'Clean new branch push');
    assert.equal(run(process.execPath, [policy, '--pre-push'], { input: `(delete) ${zeros} refs/heads/old ${head}\n` }).status, 0, 'Branch deletion');

    const remote = join(fixture, 'remote.git');
    git(['init', '--bare', '--quiet', '--template=', remote]);
    git(['push', '--quiet', remote, `${head}:refs/heads/main`]);
    denied(run('git', ['push', remote, `${descendant}:refs/heads/unsafe`]), 'Real Git push hook');
    assert.equal(git(['ls-remote', remote, 'refs/heads/unsafe']), '', 'Rejected push must not create a remote branch');

    const eventPath = join(fixture, 'event.json');
    const pr = { user: { login: 'giovannijecha' }, title: 'Check CLI compatibility', body: null, head: { sha: head } };
    writeFileSync(eventPath, JSON.stringify({ pull_request: pr }));
    assert.equal(run(process.execPath, [policy, '--event', eventPath]).status, 0, 'Clean pull request');
    writeFileSync(eventPath, JSON.stringify({ pull_request: { ...pr, body: 'Generated with an unknown assistant' } }));
    denied(run(process.execPath, [policy, '--event', eventPath]), 'Pull request attribution');
    writeFileSync(eventPath, JSON.stringify({ pull_request: { ...pr, user: { login: 'unknown-assistant' } } }));
    denied(run(process.execPath, [policy, '--event', eventPath]), 'Pull request author');
  } finally {
    const actual = realpathSync(fixture);
    const boundary = realpathSync(scratch) + sep;
    assert.ok(actual.startsWith(boundary), 'Fixture cleanup must stay inside project scratch');
    rmSync(actual, { recursive: true, force: true });
  }
});
